services:
  backend:
    build: backend
    container_name: quack_api
    ports:
      - "5001:5001"
    networks:
      - apinet
  webserver:
    build: frontend
    container_name: quack_apache
    ports:
      - "80:80"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
  apinet:
    driver: bridge
